Repository URECA-UFit/ufit-fe, pull requests merged in 2025-06, with the labels that each got.

#9 Feat: 요금제 상세 페이지 구현
  src/router/index.js
  src/views/PlanDetailPage.vue
  src/views/RatePlanStorePage.vue
Labels: feat

#21 feat: 관리자용 요금제 조회 페이지
  src/assets/trash_can.png
  src/components/AdminMenuBar.vue
  src/router/index.js
  src/views/AdminRatePlanStorePage.vue
Labels: feat

#33 feat: 어드민 요금제 생성 API 연동
  src/views/RatePlanAddPage.vue
Labels: feat

#34 feat: 요금제 목록 정렬 기능 추가
  src/views/PlanDetailPage.vue
  src/views/RatePlanStorePage.vue
Labels: feat

#40 feat: chatbot review api 연동
  package-lock.json
  package.json
  src/components/ChatbotReviewModal.vue
Labels: feat

#41 feat: 요금제 목록 상태 유지 및 상세페이지 UI 개선
  src/App.vue
  src/router/index.js
  src/views/PlanDetailPage.vue
  src/views/RatePlanStorePage.vue
Labels: feat

#47 [feat] 챗봇리뷰내역페이지 연동
  src/views/ChatBotReviewPage.vue
Labels: feat

#49 [Fix] 요금제 생성 시 입력 필드 수정
  src/views/RatePlanAddPage.vue
Labels: fix

#51 feat: 요금제 상세 페이지 개선
  src/views/PlanDetailPage.vue
Labels: feat

#52 feat: 할인혜택 줄바꿈 및 UI 개선
  src/views/PlanDetailPage.vue
Labels: feat

#58 fix: PlanDetailPage 혜택 파싱 오류 및 UI 개선
  src/views/PlanDetailPage.vue
Labels: fix

#66 fix: 어드민 챗봇 리뷰 페이지 스크롤 수정
  src/components/AdminMenuBar.vue
  src/views/ChatBotReviewPage.vue
Labels: fix

#67 chore: 배포
  src/components/AdminMenuBar.vue
  src/views/ChatBotReviewPage.vue
  src/views/PlanDetailPage.vue
Labels: chore

#70 Fix: 챗봇 모듈 관련 오류 해결
  src/components/ChatbotComponent.vue
  src/components/CommonHeader.vue
  src/views/LoginPage.vue
  src/views/PlanDetailPage.vue
  src/views/RatePlanStorePage.vue
Labels: fix

#78 fix: 해상도에 맞는 무한 스크롤 수정
  src/views/AdminRatePlanStorePage.vue
Labels: fix

#80 fix: 토큰 재발급 시 에러가 나면 로그아웃
  src/api/axiosInstance.js
Labels: fix

#84 fix: proxy target 변경
  src/api/axiosInstance.js
  src/main.js
  vue.config.js
Labels: fix

#93 chore: 주석 제거
  src/App.vue
  src/api/axiosInstance.js
  src/components/AdminMenuBar.vue
  src/components/ChatbotComponent.vue
  src/components/ChatbotReviewModal.vue
  src/components/CommonHeader.vue
  src/router/index.js
  src/views/AdminRatePlanStorePage.vue
  src/views/ChatBotReviewPage.vue
  src/views/DashBoardPage.vue
  src/views/LoginPage.vue
  src/views/PlanDetailPage.vue
  src/views/RatePlanAddPage.vue
  src/views/RatePlanStorePage.vue
Labels: chore
